name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/HomematicIPApi2.sln'
      WORKDIR: 'HomematicIPApi2'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
      working-directory: $WORKDIR
    
    - name: Build
      run: dotnet build $SOLUTION --no-restore --configuration $BUILD_CONFIG
      working-directory: $WORKDIR
    
    - name: Test
      env:
         accessPoint: ${{ secrets.ACCESSPOINT}}
         authToken: ${{ secrets.AUTHTOKEN}}
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-build
      working-directory: $WORKDIR
    
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dump
        path: C:\Users\runneradmin\AppData\Local\Temp\HomematicIpDump_*.json
      if: ${{ always() }}
