name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dump
        path: C:\Users\runneradmin\AppData\Local\Temp\HomematicIpDump_*.json
      if: ${{ always() }}
