name: .NET Build, Test, and Publish Nuget Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    
  workflow_dispatch:
    inputs:
        tags:
            description: 'Publish Tags'
            required: true
            type: string

env:
  VERSION: 1.0.0

defaults:
  run:
    working-directory: src

jobs:
  build:
      
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=$VERSION
    
    - name: Test
      env:
         accessPoint: ${{ secrets.ACCESSPOINT}}
         authToken: ${{ secrets.AUTHTOKEN}}
      run: dotnet test --no-build --verbosity normal
    
    - name: Pack 
      run: dotnet pack --output nupkgs --no-restore --no-build /p:PackageVersion=$VERSION
    
    - name: Push
      run: dotnet nuget push nupkgs/*.nupkg --source https://nuget.pkg.github.com/aleroe/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
